FROM dockcross/manylinux2014-x64
LABEL MAINTAINER="Pablo Hernandez Cerdan <pablo.hernandez.cerdan@outlook.com>"

#### Global Variables
ENV BUILD_PATH /work
####

WORKDIR $BUILD_PATH
ENV SR_BUILD_DIR ${BUILD_PATH}/sr-build
ENV SR_SRC_FOLDER_NAME sr-src
ENV SR_SRC_DIR ${BUILD_PATH}/${SR_SRC_FOLDER_NAME}

# Copy files from current repo into the docker container
COPY . ${SR_SRC_DIR}
# Remove _skbuild and dist folders if existant
# RUN cd ${SR_SRC_DIR} && rm -rf ./deploy/_skbuild && rm -rf ./deploy/dist

RUN ${SR_SRC_DIR}/deploy/manylinux-build-wheels.sh

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG IMAGE=wolfram_model-linux
ARG VERSION=latest
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0" \
      build_command="\
      rm -rf ./deploy/dist ./deploy/_skbuild; \
      docker build -f ./deploy/Dockerfile-dockcross-manylinux2014 . -t phcerdan/wolfram_model-linux; \
      docker cp $(docker create phcerdan/wolfram_model-linux:latest):/work/dist /tmp"
